version: '3.9'
services:
  user-service:
    build:
      context: ./services/user-service
    ports:
      - '${USER_SERVICE_PORT:-3001}:${USER_SERVICE_PORT:-3001}'

  product-service:
    build:
      context: ./services/product-service
    ports:
      - '${PRODUCT_SERVICE_PORT:-3002}:${PRODUCT_SERVICE_PORT:-3002}'

  order-service:
    build:
      context: ./services/order-service
    ports:
      - '${ORDER_SERVICE_PORT:-3003}:${ORDER_SERVICE_PORT:-3003}'

  payment-service:
    build:
      context: ./services/payment-service
    ports:
      - '${PAYMENT_SERVICE_PORT:-3004}:${PAYMENT_SERVICE_PORT:-3004}'