version: '3.9.1'
services:
  user_service:
    build:
      context: ./services/user-service
    ports:
      - '${USER_SERVICE_PORT:-3001}:${USER_SERVICE_PORT:-3001}'
    environment:
      - NODE_ENV=production

  product_service:
    build:
      context: ./services/product-service
    ports:
      - '${PRODUCT_SERVICE_PORT:-3002}:${PRODUCT_SERVICE_PORT:-3002}'
    environment:
      - NODE_ENV=production

  order_service:
    build:
      context: ./services/order-service
    ports:
      - '${ORDER_SERVICE_PORT:-3003}:${ORDER_SERVICE_PORT:-3003}'
    environment:
      - NODE_ENV=production

  payment_service:
    build:
      context: ./services/payment-service
    ports:
      - '${PAYMENT_SERVICE_PORT:-3004}:${PAYMENT_SERVICE_PORT:-3004}'
    environment:
      - NODE_ENV=production